import { writeFile, mkdir, access, constants } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, "output");

const BASE_FOLDERS = ["models", "routes", "controllers", "middleware", "utils"];

const DEFAULT_PACKAGE_JSON = JSON.stringify(
  {
    name: "generated-backend",
    version: "1.0.0",
    type: "module",
    main: "server.js",
    scripts: { start: "node server.js", dev: "node --watch server.js" },
    dependencies: {
      express: "^4.18.2",
      mongoose: "^7.0.0",
      dotenv: "^16.0.0",
      cors: "^2.8.5",
      bcryptjs: "^2.4.3",
      jsonwebtoken: "^9.0.0",
      helmet: "^7.0.0",
      morgan: "^1.10.0",
      "express-rate-limit": "^7.0.0",
      "express-validator": "^7.0.0",
      twilio: "^4.0.0",
      stripe: "^14.0.0",
    },
  },
  null,
  2
);

const DEFAULT_GITIGNORE = `node_modules/
.env
*.log
.DS_Store
dist/
coverage/
`;

/**
 * Ensure the output directory and all base sub-folders exist.
 */
export async function ensureOutputDir() {
  await mkdir(OUTPUT_DIR, { recursive: true });
  for (const folder of BASE_FOLDERS) {
    await mkdir(join(OUTPUT_DIR, folder), { recursive: true });
  }
}

/**
 * Write default scaffolding files if they weren't generated by DeepSeek.
 * @param {string} taskName - Used in README
 */
export async function scaffoldDefaults(taskName = "Generated Backend") {
  // package.json
  await writeIfMissing("package.json", DEFAULT_PACKAGE_JSON);

  // .gitignore
  await writeIfMissing(".gitignore", DEFAULT_GITIGNORE);

  // README.md
  const readme = generateReadme(taskName);
  await writeIfMissing("README.md", readme);
}

async function writeIfMissing(filename, content) {
  const filePath = join(OUTPUT_DIR, filename);
  try {
    await access(filePath);
    // File already exists — skip
  } catch {
    await writeFile(filePath, content, "utf8");
    console.log(`  📄 Scaffolded default: ${filename}`);
  }
}

function generateReadme(taskName) {
  return `# ${taskName}

> Auto-generated by AI Dev System (Claude + DeepSeek)

## Setup

\`\`\`bash
npm install
cp .env.example .env   # fill in your values
node server.js
\`\`\`

## Environment Variables

| Variable | Description |
|----------|-------------|
| PORT | Server port (default 3000) |
| MONGO_URI | MongoDB connection string |
| JWT_SECRET | Secret for signing JWTs |
| JWT_EXPIRES_IN | Token expiry e.g. 7d |
| TWILIO_ACCOUNT_SID | Twilio account SID |
| TWILIO_AUTH_TOKEN | Twilio auth token |
| TWILIO_WHATSAPP_FROM | WhatsApp sender number |
| STRIPE_SECRET_KEY | Stripe secret key |
| VAT_RATE | UAE VAT rate (0.05) |

## API Base URL

\`\`\`
http://localhost:3000/api/v1
\`\`\`

## Project Structure

\`\`\`
├── models/          Mongoose schemas
├── routes/          Express route handlers
├── controllers/     Business logic (if applicable)
├── middleware/      Auth, validation, error handling
├── utils/           VAT, loyalty, availability helpers
├── app.js           Express app setup
└── server.js        Entry point
\`\`\`
`;
}

/**
 * Strip markdown code fences if DeepSeek wraps output in them.
 */
function stripCodeFences(code) {
  return code
    .replace(/^```[\w]*\n?/m, "")
    .replace(/\n?```$/m, "")
    .trim();
}

/**
 * Save generated code to the output directory.
 * Automatically creates nested directories (e.g. models/Booking.js).
 * @param {string} code - Raw code string from DeepSeek
 * @param {string} filename - Relative path (e.g. "routes/bookings.js")
 * @returns {Promise<string>} - Absolute output path
 */
export async function fileExists(filename) {
  try {
    await access(join(OUTPUT_DIR, filename), constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export async function saveFile(code, filename) {
  const clean = stripCodeFences(code);
  const outputPath = join(OUTPUT_DIR, filename);
  const outputDir = dirname(outputPath);

  await mkdir(outputDir, { recursive: true });
  await writeFile(outputPath, clean, "utf8");
  return outputPath;
}
